import { type TestFormValues } from "@/lib/validations/test"

export const FORM_DEFAULTS: TestFormValues = {
  riMin: "",
  riMax: "",
  sg: "",
  hardnessMin: "",
  hardnessMax: "",
  species: "",
  selectedVariety: "",
  itemDescription: "",
  colour: "",
  clarityGrade: "",
  grade: "",
  polishingGrade: "Fine",
  proportionGrade: "Fine",
  cuttingGrade: 0,
  colourGrade: 0,
  finalGrade: 0,
  cuttingShape: "",
  crownStyle: "",
  pavilionStyle: "",
  messurementX: "",
  messurementY: "",
  messurementZ: "",
  transparency: "",
  origin: "",
  spectroscopy: "",
  comments: "",
  specialNote: "",
  treatment: "",
  clarityEnhancement: "",
  isHeated: false,
  isEmerald: false,
  isMixCut: false,
}
